config/routes.rb
NewStore::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get 'search' => 'search#new', as: 'search'
  post 'search' => 'search#show', as: 'searches'
  post 'search_product' => 'search#product', as: 'search_product'

  resources :orders, except: [] do
    collection do
      # post '/create' => "orders#create", as: 'create'
      get '/filter' => 'orders#filter', as: 'filter'
      get '/new' => 'orders#new'
    end
    get '/change_status' => 'orders#change_status', as: 'change_status'
  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:edit, :update, :create]
  end

  resources :sales

  namespace :admin do
    resources :types
    resources :products
  end

  get '/cart' => 'carts#show'


  resources :users do
    member do
      get '/cart' => 'carts#show', as: 'cart'
    end
  end

  get 'add_to_cart' => 'product_cart_manager#join'
  get 'remove_from_cart' => 'product_cart_manager#destroy'

  resources :categories, only: [:index, :show]
  root to: 'products#index'

end

app/views/menu/_admin_menu.html.haml
%li.divider-vertical
%li.dropdown
  %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
    Dashboard
    %b.caret
  %ul.dropdown-menu
    %li=link_to "Warehouse", admin_products_path
    %li=link_to "Sales menu", sales_path
    %li=link_to "Users", users_path
    %li=link_to "Search", search_path
    %li=link_to "New product", new_admin_product_path
    %li=link_to "Category management", new_admin_type_path

app/views/menu/_big_product_image.html.haml
.big_product_container
  .big_product_image
    .image
    .caption

app/views/menu/_carousel.html.haml
.carousel.slide#myCarousel
  -item_thing.photos.size.times do |i|
    %ol.carousel-indicators
      %li{data: {target: '#myCarousel'}, class: "#{'active' if i == 1}"}
  .carousel-inner
    -item_thing.photos.each do |photo|
      .item
        =image_tag photo.url
  = link_to "<", "#myCarousel", {class: 'left carousel-control', data: {slide: 'prev'}}
  = link_to ">", "#myCarousel", {class: 'right carousel-control', data: {slide: 'next'}}

app/views/menu/_categories.html.haml
%ul.nav.nav-tabs.right_menu
  %li{class: "category all #{'active' if 'products' == params[:controller] && 'index' == params[:action]}" }
    =link_to "All products", products_path, remote: true
  -Category.all.each do |category|
    %li{class: "category #{'active' if category.id.to_s == params[:id]}", id: category.id }
      =link_to category.name, category_path(category), remote: true

app/views/menu/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-error">
            The form contains <%= pluralize(object.errors.count, "error") %>.
        </div>
        <ul>
        <% object.errors.full_messages.each do |msg|%>
            <li>* <%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/menu/_footer.html.haml
-4.times do
  .some_link= link_to Faker::Lorem.word, '#'

app/views/menu/_right.html.haml
%ul.nav.nav-tabs.right_menu
  %li{class: "category all #{'active' if 'products' == params[:controller] && 'index' == params[:action]}" }
    =link_to "All products", products_path, remote: true
  -Category.all.each do |category|
    %li{class: "category #{'active' if category.id.to_s == params[:id]}", id: category.id }
      =link_to category.name, category_path(category), remote: true

app/views/menu/_top_bar.html.haml
.top_bar
.navbar
  .navbar-inner
    .brand=link_to "Shop", root_url
    %a.span6.btn.btn-primary.btn-navbar{data: {toggle: 'collapse', target: '.nav-collapse'}}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .nav-collapse.collapse
      %ul.nav
        %li=link_to current_user_presenter, user_path(current_user)
        %li=link_to "Products", products_path
        %li=link_to "My cart", cart_path
        %li=link_to "Orders", orders_path
        = render 'menu/admin_menu' if current_user_presenter.admin?
        .span1
        %li
          =form_tag(search_product_path, class: 'navbar-form') do
            .input-append
              = text_field_tag :search, nil, {class: 'span2', placeholder: 'Find product'}
              = submit_tag 'Search', {class: 'btn'}
      %ul.nav.pull-right
        = render 'sessions/menu', log_in: current_user_presenter.guest?