config/routes.rb
NewStore::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get 'search' => 'search#new', as: 'search'
  post 'search' => 'search#show', as: 'searches'
  post 'search_product' => 'search#product', as: 'search_product'

  resources :orders, except: [] do
    collection do
      # post '/create' => "orders#create", as: 'create'
      get '/filter' => 'orders#filter', as: 'filter'
      get '/new' => 'orders#new'
    end
    get '/change_status' => 'orders#change_status', as: 'change_status'
  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:edit, :update, :create]
  end

  resources :sales

  namespace :admin do
    resources :types
    resources :products
  end

  get '/cart' => 'carts#show'


  resources :users do
    member do
      get '/cart' => 'carts#show', as: 'cart'
    end
  end

  get 'add_to_cart' => 'product_cart_manager#join'
  get 'remove_from_cart' => 'product_cart_manager#destroy'

  resources :categories, only: [:index, :show]
  root to: 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  # extend TotalPrice

  CURRENCY = 'USD'
  NO_PRICE = Money.new(0, CURRENCY)
  QUERY_PRICE_WITH_DISCOUNT = 'products.base_price_cents * ( 1.0 - products.discount/100.0)'
  
  def discount_price_calc
    self.base_price*(1 - self.discount/100.0) || NO_PRICE
  end

  paginates_per 9

  monetize :base_price_cents

  attr_accessible :title, :description, :base_price_cents, :discount, :quantity, :on_sale, :base_price, :price_cents

  validates :title, presence: true, uniqueness: true
  validates_presence_of :description
  validates :base_price_cents, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0}, presence: true
  validates :quantity, presence: true, numericality: {greater_than_or_equal_to: 0, integer: true}

  scope :find_on_sale, ->{where(on_sale: true)}

  belongs_to :order

  has_many :list_items
  has_many :users, through: :list_items, source: :holder, source_type: "User"

  has_many :category_products
  has_many :categories, through: :category_products

  has_many :reviews, order: 'created_at desc'
  has_many :assets

  has_and_belongs_to_many :sales

  after_create :create_asset
  before_save :save_total_discount

  accepts_nested_attributes_for :assets, :sales

  delegate :rating, to: :reviews
  delegate :get_discount, to: :sales
  delegate :photos, to: :assets
  delegate :quantity_all, to: :list_items

  include PgSearch
  pg_search_scope :search_by_title_or_description, against: [:title, :description]

  class << self

    def start_selling
      update_all(on_sale: true);
    end

    def on_sale?
      where(on_sale: true).count == count
    end

    def retire
      update_all(on_sale: false)
    end

    def set_discount discount, name=nil
      all.each do |product|
        product.set_discount discount, name
      end
    end

    def total_price par=nil
      # all.reduce(NO_PRICE){|sum, p| sum += p.total_price par} 
      Money.new(sum(QUERY_PRICE_WITH_DISCOUNT), CURRENCY)
    end

    def get_discount
      all.map{|product| product.get_discount }.max
    end
  end

  def total_price par=nil
   return base_price || NO_PRICE if par == 'base'
   return discount_price_calc
 end

 def add param
  param.each do |name, items|
    send "add_#{name}", items
  end
end

{'start_selling' => true, 'retire' => false}.each do |name, on_sale_value|
  define_method name do
    self.on_sale = on_sale_value
    save
  end
end

def set_discount percent, name=nil
  sales << Sale.set_discount(percent, name); save
end

def self.on_discount?
  joins(:sales).count > 0
end

def on_discount?
  sales.count > 0
end

def off_discount identifier=nil
  sales.destroy_all; save
end

def out_of_stock?
  quantity == in_carts
end

def in_carts
  list_items.quantity_all
end

def on_sale?
  on_sale && any_left_in_warehouse?
end

def any_left_in_warehouse?
 ListItem.where_product(self).sum(:quantity) < quantity 
end

private

def create_asset
  assets.create
end

def add_category category
  Category.get(category).add product: self
end

def add_review review
  reviews << review
end

def add_photos photos
  photos.each do |photo|
    assets.create({photo: photo})
  end
end

def save_total_discount
  self.discount = get_discount || 0
end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_filter :authorize_admin
  layout 'admin_application'

  def index
    @products = Product.unscoped.page params[:page]
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if params[:assets]
      @photos = params[:assets][:photos]
      @product.add photos: @photos
    end

    if @product.update_attributes(params[:product])
      redirect_to admin_products_path, notice: "Successfully updated product"
    else
      redirect_to edit_admin_product_path(@product), notice: "Error"
    end
  end

  def create

    product = Product.new(params[:product])

    product.start_selling

    if product.save
      if params[:assets]
        @photos = params[:assets][:photos]
        product.add photos: @photos
      end
      redirect_to products_path, notice: "Successfully created product"
    else
      redirect_to new_admin_product_path, notice: "Error"
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :authorize_admin, except: [:index, :show]

	def index
		@products = Product.find_on_sale.page params[:page]
	end


	def show
		@product = ProductPresenter.new Product.includes(:reviews, reviews: :user).find(params[:id]), current_user
	end

end

app/helpers/products_helper.rb
module ProductsHelper
  def product_price product
    text = "<b>$#{product.price}</b>"
    if product.on_discount?
      text = "Was <strike>$#{product.base_price}</strike>. Now, only " + text
    else
      text = "Only " + text
    end
    raw text
  end

  def adding_text product
    return 'Sorry, we have no more' if product.out_of_stock?
    product.users.include?(current_user) ? "Add more" : "Add to cart"
  end

  def adding_class product
    klass = []
    klass << (product.belongs_to_user? ? 'many' : 'single')
    klass << ( product.out_of_stock? ? 'disabled' : '')
    klass.join(' ')
  end

  def quantity product
    if product.belongs_to_user?
      text = content_tag :div, class: 'quantity' do
        "#{product.quantity_for_user} in cart"
      end
    else
      ''
    end
  end

  def remove product
    text = ''
    if product.users.include?(current_user)
      text = content_tag :div, class: 'remove' do
        link_to "Remove from cart", remove_from_cart_path({user_id: current_user, product: product}), remote: true
      end
    end
    text
  end

  def saving_text product
    "You pay only #{product.discount}%!" if product.on_discount?
  end
end

app/views/products/_product.html.haml
-product_counter ||= nil
.product.inline{class: product.title_param, id: product_counter}
  .span7.title= link_to product.title, product_path(product), {data: {photo: product.photo.url, title: product.title }}
  .span1.price= "$#{product.price}"
  .span2.quantity= product.quantity_for_user
  .span2.remove= link_to "X", remove_from_cart_path({user_id: current_user.id, product: product.id}), confirm: 'U cereal?'

app/views/products/_short.html.haml
-product_counter ||= nil
.span4.product.short.well{class: product.title_param, id: product_counter }
  .row.span12
    .product_thumbnail.thumbnail{data: {photo: product.photo.url, title: product.title}}
      = link_to image_tag(product.photo.url), product_path(product)
  .row.span12
    %h3.title=link_to product.title_shorter, product_path(product), {data: {photo: product.photo.url, title: product.title}}
  .row.span12
    .price= product_price product
  .row.span12
    .price.discount= saving_text product
  .row.span12
    =link_to adding_text(product), add_to_cart_path({user_id: current_user.id, product: product}), remote: true, class: "span12 btn btn-primary cart_btn #{adding_class product}" , data: {:'loading-text' => 'Processing...'}
  .row.span12
    .quantity= quantity product
    .remove= remove product

app/views/products/_table_header.html.haml
.header
  .span7.title
    Title
  .span1.price
    Price
  .span2.quantity
    Quantity
  .span2
    Remove

app/views/products/index.html.haml
.paginate= paginate @products, remote: true
.products.span12
  =render partial: 'products/short', collection: presentify(@products, current_user), as: :product
.paginate= paginate @products, remote: true
- content_for(:category_bar) do
  =render 'menu/categories'

app/views/products/index.js.erb
$('.products').html("<%= j render partial: 'products/short', collection: presentify(@products, current_user), as: :product %>");
  $('.paginate').html("<%= j paginate @products, remote: true %>");


$(function() {
  // $('.cart_btn').bind('ajax:beforeSend', function() {
  //   $(this).button("loading")
  // });
  // $('.cart_btn').bind('ajax:success', function() {
  //   $(this).button('reset');
  // });

$('.cart_btn').on('click', function() {
  $(this).css('height', '1em');
});

  $(".product_thumbnail, .product .title a").on('mouseenter', update_big_image);
  $('li.category').removeClass("active");
  $("li.category.all").addClass("active");
});

app/views/products/list.html.haml
.products
  - if @products.empty?
    Nothing found
  - else
    =render 'products/table_header'
    =render presentify(@products)

app/views/products/new.html.haml
%h3 New product
.span8=render partial: 'form', locals: { product: @product}

app/views/products/show.html.haml
.product.product_full.span12
  .row.top_title
    .span9.title
      %h1= @product.title
    %h2
      .discount.span1= @product.discount
      .price.span2= humanized_money_with_symbol @product.price
  .row.note_bar
    .overall_note= note_in_stars @product.rating
  .row.buttons
    %h2.btn.btn-primary.add_to_cart
      = link_to("Add to cart", add_to_cart_path({user_id: current_user.id, product: @product.id})) if @product.on_sale?
    .span2=link_to 'Edit product', edit_admin_product_path(@product) if current_user.admin?
    .span2.order_product= link_to_unless current_user.guest?, 'Order', '#'
  .row.overview
    .span6
      = render partial: 'menu/carousel', locals: {item_thing: @product}
    .span6
      .row
        %p.description
          = @product.description
      .row.categories
        Categories:
        = @product.list_categories
        .add_to_category= link_to_if current_user.admin?, "Add to category", edit_admin_type_path(@product)
  .row.review_bar.span12
    .span12=render partial: 'reviews/new', locals: {product: @product.product, review: Review.new}
  .row.reviews.span12
    =render @product.reviews, product: @product

app/views/products/show.js.erb
$('.reviews').html("<%= j render @product.reviews %>");
$('.overall_note').html("<%= note_in_stars(@product.rating) %>");

app/views/products/update_product.js.erb
$('.product.short.' + "<%= j @product_presenter.title_param %>")
  .replaceWith("<%= j render( partial: 'products/short', locals: {product: @product_presenter}) %>");

$('.products .inline.' + "<%= j @product_presenter.title_param %>")
  .replaceWith("<%= j render @product_presenter if @product_presenter %>");
$('.product.short.' + "<%= j @product_presenter.title_param %>" + 'a.btn.disabled')
  .button('reset');

  onWidthChanges();
   // $(".product_thumbnail, .product .title a").on('mouseenter', update_big_image);