config/routes.rb
NewStore::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get 'search' => 'search#new', as: 'search'
  post 'search' => 'search#show', as: 'searches'
  post 'search_product' => 'search#product', as: 'search_product'

  resources :orders, except: [] do
    collection do
      # post '/create' => "orders#create", as: 'create'
      get '/filter' => 'orders#filter', as: 'filter'
      get '/new' => 'orders#new'
    end
    get '/change_status' => 'orders#change_status', as: 'change_status'
  end

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:edit, :update, :create]
  end

  resources :sales

  namespace :admin do
    resources :types
    resources :products
  end

  get '/cart' => 'carts#show'


  resources :users do
    member do
      get '/cart' => 'carts#show', as: 'cart'
    end
  end

  get 'add_to_cart' => 'product_cart_manager#join'
  get 'remove_from_cart' => 'product_cart_manager#destroy'

  resources :categories, only: [:index, :show]
  root to: 'products#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base

  has_and_belongs_to_many :products
  has_and_belongs_to_many :categories

  attr_accessible :name, :discount

  validates :discount, numericality: {greater_than: 0, less_than: 100 }, presence: true

  class << self

    def new_from_params params
      sale = where(name: params[:name_from_select])
      .first_or_initialize

      sale.discount = params[:discount] if sale.new_record?

      products_id = params[:products] ? params[:products].keys : []

      if params[:categories].presence
        categories_id = params[:categories].keys
        products_id << CategoryProduct.where(category_id: categories_id).pluck(:product_id)
        sale.categories << Category.find(categories_id)
      end

      sale.products << Product.find(products_id)
      sale.name = params[:name] unless params[:name].blank?
      sale.save
      sale
    end

    def get_discount
      maximum(:discount) || 0
    end

    def set_discount percent, name=nil
      create(discount: percent, name: name)
    end

    def get_by_identifier identifier
      case identifier.class
      when String then where(name: identifier)
      when Fixnum then where(discount: identifier)
      else scoped
      end
    end
  end

  def remove params={}
   remove_product params[:product] if params[:product]
   Sale.delete self if params.empty?
 end

 private

 def remove_product product
  products.delete product
end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_filter :authorize_admin

  def new
    @categories = Category.all
    @products, @checked = if params[:product]
      [[Product.find(params[:product])], true]
    else
      [ Product.all, false ]
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.remove unless params[:product]
    if params[:product]
      product = Product.find(params[:product])
      @sale.remove product: product
    end
    @sales = Sale.all

    respond_to do |format|
      format.html {redirect_to sales_url}
      format.js {render :index}
    end
  end

  def index
    @sales = Sale.all
  end

  def create
    @sale = Sale.new_from_params params
# binding.pry
    if @sale.save
      flash[:notice] = "Successfully created sale"
      redirect_to sales_path
    else
      @categories = Category.all
      @products = Product.all
      flash[:errors] = "Something went wrong"
      render :new
    end
  end
end

app/views/sales/_inline_product.html.haml
.row
  .span12.product.inline.row{class: product.title_param}
    .span6.title= link_to product.title, product_path(product), {data: {photo: product.photo.url, title: product.title }}
    .span1.base_price= "$#{product.base_price}"
    .span1.price= "$#{product.price}"
    .span1.discount= "#{product.discount}%"
    .span1.quantity= product.quantity
    .span1.remove_product= link_to "X", sales_path({sale: sale, product: product}), method: :delete, remote: true

app/views/sales/_products_list.html.haml
.row.table_header
  .span6.title
    Title
  .span1.base_price
    Base Price
  .span1.price
    Price
  .span1.discount
    Discount
  .span1.quantity
    Quantity
  .span1
    Remove
=render partial: 'inline_product', collection: products, as: :product, locals: {sale: sale}

app/views/sales/_sale.html.haml
.sale
  .row
    %h4.span7= sale.name.blank? ? "Unnamed" : sale.name
    .span1
    %h4.span2= "#{sale.discount}%"
    %h4.span2.remove.sale= link_to "X", sale_path(sale), method: :delete, remote: true
  .row
    = render partial: 'products_list', locals: {sale: sale, products: presentify(sale.products)}

app/views/sales/index.html.haml
%h3= link_to "New sale", new_sale_path, class: 'btn btn-primary'
.row
  .span1
  .sales.span11
    = render @sales
= javascript_include_tag 'pages/sale'

app/views/sales/index.js.erb
$('.sales').html("<%= j render(@sales) %>");
$('.footer').html("<%= j render 'menu/footer' %>");

$(function() {

  $('.product > .remove.product > a').on( 'click', function() {

   $(this).closest('.product').slideUp();
  });
   $('.sale > .remove.sale > a').on( 'click', function() {

   $(this).closest('.sale').slideUp();
  });
});

app/views/sales/new.html.haml
%h3 Sales
.new_sales
  =form_tag sales_path do
    = render 'menu/errors', object: @sale if @sale
    .row
      .span1
      .span11
        = submit_tag "Submit", class: 'btn btn-primary'
        .row
          .span3.name
            = label_tag :name, "Sale name"
            = text_field_tag :name, '', {placeholder: "Can be blank"}
          .span1
          .span5
            = label_tag :name_from_select
            = select_tag :name_from_select, options_from_collection_for_select(Sale.all, 'name', 'name'), include_blank: ''
          .span3.discount
            = label_tag :discount, "Discount"
            = number_field_tag :discount, '', {value: 100, max: 100, min: 0, class: 'input-mini'}
            %span.help-inline Percent of base price
    .row
      .span1
      .span4.categories
        %h3 Category
        - @categories.each do |category|
          .category
            .check_form= check_box_tag "categories[#{category.id}]", category.name
            .label_form= label_tag "categories[#{category.id}]", category.name
      .span1
      .span5.products
        %h3 Product
        - @products.each do |product|
          .product
            .check_form= check_box_tag "products[#{product.id}]", product.title, @checked
            .label_form= label_tag "products[#{product.id}]", product.title
      .span1